baseURL = "https://the-way-of-emacs.org/"
languageCode = "en-us"
title = "The Way of Emacs"
theme = "hugo-dusk"
defaultContentLanguage = "en"
enableRobotsTXT = true

# Params for Hugo Dusk
[params]
  description = "A myth-bound novel written in public, through the lens of Emacs, org-mode, and other sacred texts."
  accentColor = "#f97316"  # Tailwind orange-500-ish
  dateFormat = "2006-01-02"
  backgroundImage = "images/dragon-backdrop.jpg"  # We'll add this file
  logo = "images/sigil.png"  # Optional sigil/crest/icon
  headerImage = "images/neptune-dragon.jpg"
  [params.author]
    name = "Stormrider, the Rift Archivist"

# Optional: Social Links
[[params.social]]
  name = "GitHub"
  icon = "fa fa-github"
  url = "https://github.com/YOURUSERNAME"

[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon"
  url = "https://mastodon.social/@yourhandle"

# Menu (feel free to change slugs as you build)
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "The Novel"
  url = "/novel/"
  weight = 2

[[menu.main]]
  name = "Lore"
  url = "/lore/"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5
